### PR TITLE
fix: new arch pod install error

### PR DESCRIPTION
**Pull request by batuhansahan**
fixes https://github.com/jakex7/react-native-localization-settings/issues/5

need pr and test.

### CODE REVIEW

**Review by orcunorcun — APPROVED** [review]
It fixed the issue. Thanks!

**Comment by engmagdy87** [comment]
can u release this fix as i faced the same issue

**Comment by hromovp** [comment]
Hi, I have the same issue and wondering when fix will be released

**Comment by 7ammer** [comment]
Can we get this merged?

**Comment by engmagdy87** [comment]
@jakex7

**Comment by olivierhill** [comment]
Another vote for this here 😄

**Comment by denysoleksiienko** [comment]
How to install or apply this fix with yarn 1.22.22?

**Comment by hexadecy** [comment]
This also fixes an pod install issue on the old arch with react-native 0.74

**Review by jakex7 — APPROVED** [review]
Hey @batuhansahan and the entire community gathered around this library. I apologize for not responding for such a long time, but due to the fact that this project is maintained only by me and in my private time after my regular job, I can't always take care of it in the time I would like to. To sum up the above, thank you all for your support in helping to maintaining this project!

**Pull request merged**
